// Generated by CoffeeScript 1.6.2
(function() {
  exports.quote = 1;

  exports.if_ = 2;

  exports.begin = 3;

  exports.assign = 4;

  exports.vari = 5;

  exports.lamda = 6;

  exports.let_ = 7;

  exports.letrec = 8;

  exports.macro = 9;

  exports.funcall = 10;

  exports.macrocall = 11;

  exports.jscallable = 12;

  exports.jsobject = 13;

  exports.jsrequire = 14;

}).call(this);

/*
//@ sourceMappingURL=keywords.map
*/
