// Generated by CoffeeScript 1.6.2
(function() {
  var compile, dao, solve, xexports, _ref;

  _ref = dao = require('../lib/dao'), solve = _ref.solve, compile = _ref.compile;

  xexports = {};

  exports.Test = {
    "test atomic": function(test) {
      test.equal(solve('1'), 1);
      test.equal(solve('123'), 123);
      test.equal(solve('-123.56e-3'), -123.56e-3);
      test.equal(solve('"1"'), "1");
      test.equal(solve('3'), 3);
      return test.done();
    },
    "test string": function(test) {
      test.equal(solve('1+1'), 2);
      return test.done();
    }
  };

}).call(this);

/*
//@ sourceMappingURL=test_dao.map
*/
