// Generated by CoffeeScript 1.6.2
(function() {
  var parse, xexports;

  parse = require("../lib/leftrecursive.js").parse;

  xexports = {};

  exports.Test = {
    "test A: Ax|a; B:A|b": function(test) {
      test.equal(parse('a'), 'a');
      test.equal(parse('ax'), 'ax');
      test.equal(parse('axx'), 'axx');
      test.equal(parse('axxx'), 'axxx');
      test.equal(parse('bxxx'), 'bxxx');
      return test.done();
    }
  };

}).call(this);

/*
//@ sourceMappingURL=testLeftRecursive.map
*/
