// Generated by CoffeeScript 1.6.2
(function() {
  var add, compile, core, coreSolve, dao, neg, solve, string, util, xexports, _ref, _ref1;

  _ref = util = require('../lib/util'), string = _ref.string, add = _ref.add, neg = _ref.neg;

  core = require('../lib/core');

  _ref1 = dao = require('../lib/dao'), solve = _ref1.solve, compile = _ref1.compile;

  coreSolve = core.solve;

  coreSolve = function(v) {
    return v;
  };

  xexports = {};

  exports.Test = {
    "test atomic": function(test) {
      test.equal(solve('3'), 3);
      test.equal(solve('123'), 123);
      test.deepEqual(solve('-123.56e-3'), coreSolve(neg(0.12356)));
      test.deepEqual(solve('"1"'), coreSolve(string('"1"')));
      return test.done();
    },
    "test add": function(test) {
      test.deepEqual(solve('1+1'), coreSolve(add(1, 1)));
      test.deepEqual(solve('(1+1)'), coreSolve(add(1, 1)));
      test.deepEqual(solve('(1+1)+1'), coreSolve(add(add(1, 1), 1)));
      return test.done();
    }
  };

}).call(this);

/*
//@ sourceMappingURL=test_dao.map
*/
