// Generated by CoffeeScript 1.6.2
(function() {
  var StateMachine, compile, core, dao, daoutil, readToken, solve, string, util, xexports, _ref, _ref1;

  string = (util = require('../lib/util')).string;

  core = require('../lib/core');

  _ref = dao = require('../lib/dao'), solve = _ref.solve, compile = _ref.compile;

  _ref1 = daoutil = require('../lib/daoutil'), StateMachine = _ref1.StateMachine, readToken = _ref1.readToken;

  xexports = {};

  exports.Test = {
    "test StateMachine.match": function(test) {
      var sm;

      sm = new StateMachine([['if', 'if'], ['iff', 'iff'], ['else', 'else']]);
      test.deepEqual(sm.match('if', 0), ['if', 2]);
      test.deepEqual(sm.match('iff', 0), ['iff', 3]);
      test.deepEqual(sm.match('ifg', 0), ['if', 2]);
      test.deepEqual(sm.match('i', 0), [null, 1]);
      test.deepEqual(sm.match('ig', 0), [null, 1]);
      test.deepEqual(sm.match('x', 0), [null, 0]);
      test.deepEqual(sm.match('if ', 0), ['if', 2]);
      test.deepEqual(sm.match('else ', 0), ['else', 4]);
      return test.done();
    }
  };

}).call(this);

/*
//@ sourceMappingURL=test_daoutil.map
*/
