// Generated by CoffeeScript 1.6.2
(function() {
  var core;

  exports.core = core = require("./lib/core");

  exports.solve = core.solve;

  exports.compile = core.compile;

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
