// Generated by CoffeeScript 1.6.2
(function() {
  var core, fun, special,
    __slice = [].slice;

  core = require("../core");

  fun = core.fun;

  special = core.special;

  exports.print_ = special(null, 'print_', function() {
    var args, cont, solver;

    solver = arguments[0], cont = arguments[1], args = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
    return solver.argsCont(args, function(args, solver) {
      console.log.apply(console, args);
      return cont(null);
    });
  });

  exports.eq = special(2, 'eq', function(solver, cont, x, y) {
    var xcont, ycont;

    ycont = solver.cont(y, function(v) {
      return cont(x === v);
    });
    xcont = function(v) {
      x = v;
      return ycont(null);
    };
    return solver.cont(x, xcont);
  });

  exports.ne = special(2, 'ne', function(solver, cont, x, y) {
    var xcont, ycont;

    ycont = solver.cont(y, function(v) {
      return cont(x !== v);
    });
    xcont = function(v) {
      x = v;
      return ycont(null);
    };
    return solver.cont(x, xcont);
  });

  exports.lt = special(2, 'lt', function(solver, cont, x, y) {
    var xcont, ycont;

    ycont = solver.cont(y, function(v) {
      return cont(x <= v);
    });
    xcont = function(v) {
      x = v;
      return ycont(null);
    };
    return solver.cont(x, xcont);
  });

  exports.le = special(2, 'le', function(solver, cont, x, y) {
    var xcont, ycont;

    ycont = solver.cont(y, function(v) {
      return cont(x <= v);
    });
    xcont = function(v) {
      x = v;
      return ycont(null);
    };
    return solver.cont(x, xcont);
  });

  exports.gt = special(2, 'gt', function(solver, cont, x, y) {
    var xcont, ycont;

    ycont = solver.cont(y, function(v) {
      return cont(x > v);
    });
    xcont = function(v) {
      x = v;
      return ycont(null);
    };
    return solver.cont(x, xcont);
  });

  exports.ge = special(2, 'ge', function(solver, cont, x, y) {
    var xcont, ycont;

    ycont = solver.cont(y, function(v) {
      return cont(x >= v);
    });
    xcont = function(v) {
      x = v;
      return ycont(null);
    };
    return solver.cont(x, xcont);
  });

  exports.add = special(2, 'add', function(solver, cont, x, y) {
    var xcont, ycont;

    ycont = solver.cont(y, function(v) {
      return cont(x + v);
    });
    xcont = function(v) {
      x = v;
      return ycont(null);
    };
    return solver.cont(x, xcont);
  });

  exports.sub = special(2, 'sub', function(solver, cont, x, y) {
    var xcont, ycont;

    ycont = solver.cont(y, function(v) {
      return cont(x - v);
    });
    xcont = function(v) {
      x = v;
      return ycont(null);
    };
    return solver.cont(x, xcont);
  });

  exports.mul = special(2, 'mul', function(solver, cont, x, y) {
    var xcont, ycont;

    ycont = solver.cont(y, function(v) {
      return cont(x * v);
    });
    xcont = function(v) {
      x = v;
      return ycont(null);
    };
    return solver.cont(x, xcont);
  });

  exports.div = special(2, 'div', function(solver, cont, x, y) {
    var xcont, ycont;

    ycont = solver.cont(y, function(v) {
      return cont(x / v);
    });
    xcont = function(v) {
      x = v;
      return ycont(null);
    };
    return solver.cont(x, xcont);
  });

  exports.mod = special(2, 'mod', function(solver, cont, x, y) {
    var xcont, ycont;

    ycont = solver.cont(y, function(v) {
      return cont(x % v);
    });
    xcont = function(v) {
      x = v;
      return ycont(null);
    };
    return solver.cont(x, xcont);
  });

  exports.and_ = special(2, 'and_', function(solver, cont, x, y) {
    var xcont, ycont;

    ycont = solver.cont(y, function(v) {
      return cont(x && v);
    });
    xcont = function(v) {
      x = v;
      return ycont(null);
    };
    return solver.cont(x, xcont);
  });

  exports.or_ = special(2, 'or_', function(solver, cont, x, y) {
    var xcont, ycont;

    ycont = solver.cont(y, function(v) {
      return cont(x && v);
    });
    xcont = function(v) {
      x = v;
      return ycont(null);
    };
    return solver.cont(x, xcont);
  });

  exports.not_ = special(1, 'not_', function(solver, cont, x) {
    return solver.cont(x, function(v) {
      return cont(!v);
    });
  });

  exports.lshift = special(2, 'lshift', function(solver, cont, x, y) {
    var xcont, ycont;

    ycont = solver.cont(y, function(v) {
      return cont(x << v);
    });
    xcont = function(v) {
      x = v;
      return ycont(null);
    };
    return solver.cont(x, xcont);
  });

  exports.rshift = special(2, 'rshift', function(solver, cont, x, y) {
    var xcont, ycont;

    ycont = solver.cont(y, function(v) {
      return cont(x >> v);
    });
    xcont = function(v) {
      x = v;
      return ycont(null);
    };
    return solver.cont(x, xcont);
  });

  exports.bitand = special(2, 'bitand', function(solver, cont, x, y) {
    var xcont, ycont;

    ycont = solver.cont(y, function(v) {
      return cont(x & v);
    });
    xcont = function(v) {
      x = v;
      return ycont(null);
    };
    return solver.cont(x, xcont);
  });

  exports.bitor = special(2, 'bitor', function(solver, cont, x, y) {
    var xcont, ycont;

    ycont = solver.cont(y, function(v) {
      return cont(x | v);
    });
    xcont = function(v) {
      x = v;
      return ycont(null);
    };
    return solver.cont(x, xcont);
  });

  exports.bitnot = special(1, 'not_', function(solver, cont, x) {
    return solver.cont(x, function(v) {
      return cont(~v);
    });
  });

  exports.inc = special(1, 'inc', function(solver, cont, vari) {
    return function(v) {
      return cont(++vari.binding);
    };
  });

  exports.inc2 = special(1, 'inc2', function(solver, cont, vari) {
    return function(v) {
      vari.binding++;
      return cont(++vari.binding);
    };
  });

  exports.dec = special(1, 'dec', function(solver, cont, vari) {
    return function(v) {
      return cont(--vari.binding);
    };
  });

  exports.dec2 = special(1, 'dec2', function(solver, cont, vari) {
    return function(v) {
      vari.binding--;
      return cont(--vari.binding);
    };
  });

  exports.getvalue = special(1, 'getvalue', function(solver, cont, x) {
    return solver.cont(x, function(v) {
      return cont(solver.trail.getvalue(v));
    });
  });

  exports.length = special(1, 'length', function(solver, cont, x) {
    return solver.cont(x, function(v) {
      return cont(v.length);
    });
  });

  exports.neg = special(1, 'neg', function(solver, cont, x) {
    return solver.cont(x, function(v) {
      return cont(-v);
    });
  });

  exports.abs = special(1, 'abs', function(solver, cont, x) {
    return solver.cont(x, function(v) {
      return cont(Math.abs(v));
    });
  });

  exports.index = special(2, 'index', function(solver, cont, x, y) {
    var xcont, ycont;

    ycont = solver.cont(y, function(v) {
      return cont(x[y]);
    });
    xcont = function(v) {
      x = v;
      return ycont(null);
    };
    return solver.cont(x, xcont);
  });

  exports.first = exports.head = special(1, 'first', function(solver, cont, x) {
    return solver.cont(x, function(v) {
      return cont(v[0]);
    });
  });

  exports.tail = special(1, 'tail', function(solver, cont, x) {
    return solver.cont(x, function(v) {
      return cont(v.slice(1));
    });
  });

  exports.second = special(1, 'second', function(solver, cont, x) {
    return solver.cont(x, function(v) {
      return cont(v[1]);
    });
  });

  exports.third = special(1, 'third', function(solver, cont, x) {
    return solver.cont(x, function(v) {
      return cont(v[2]);
    });
  });

  exports.concat = special(2, 'concat', function(solver, cont, x, y) {
    var xcont, ycont;

    ycont = solver.cont(y, function(v) {
      return cont(x.concat(y));
    });
    xcont = function(v) {
      x = v;
      return ycont(null);
    };
    return solver.cont(x, xcont);
  });

  exports.list = special([], 'list', function() {
    var args, cont, solver;

    solver = arguments[0], cont = arguments[1], args = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
    return solver.argsCont(args, cont);
  });

  exports.push = special(2, 'push', function(solver, cont, x, y) {
    var xcont, ycont;

    ycont = solver.cont(y, function(v) {
      return cont(x.push(v));
    });
    xcont = function(v) {
      x = v;
      return ycont(null);
    };
    return solver.cont(x, xcont);
  });

  exports.pushp = special(2, 'pushp', function(solver, cont, x, y) {
    var xcont, ycont;

    ycont = solver.cont(y, function(v) {
      var fc;

      fc = solver.failcont;
      solver.failcont = function(v) {
        x.pop();
        return fc(v);
      };
      return cont(x.push(v));
    });
    xcont = function(v) {
      x = v;
      return ycont(null);
    };
    return solver.cont(x, xcont);
  });

  exports.free = special(1, 'freep', function(solver, cont, x) {
    return function(v) {
      return cont(solver.trail.deref(x) instanceof Var);
    };
  });

  exports.toString = special(1, 'toString', function(solver, cont, x) {
    return solver.cont(x, function(v) {
      return cont((v != null ? typeof v.toString === "function" ? v.toString() : void 0 : void 0) || JSON.stringify(v));
    });
  });

}).call(this);

/*
//@ sourceMappingURL=general.map
*/
