// Generated by CoffeeScript 1.6.2
(function() {
  var andp, begin, bind, cons, core, dightsSpaces, dummy, flatString, getvalue, is_, kleene, kleenePredicate, leftkleene, macro, memo, orp, print_, settext, solve, special, toString, vari, xexports, _ref, _ref1, _ref2, _ref3, _ref4;

  _ref = core = require("../../lib/interpreter/core"), solve = _ref.solve, special = _ref.special, vari = _ref.vari, dummy = _ref.dummy, cons = _ref.cons, vari = _ref.vari, macro = _ref.macro;

  _ref1 = require("../../lib/interpreter/builtins/general"), print_ = _ref1.print_, getvalue = _ref1.getvalue, toString = _ref1.toString;

  _ref2 = require("../../lib/interpreter/builtins/logic"), andp = _ref2.andp, orp = _ref2.orp, bind = _ref2.bind, is_ = _ref2.is_;

  begin = require("../../lib/interpreter/builtins/lisp").begin;

  _ref3 = require("../../lib/interpreter/builtins/parser"), settext = _ref3.settext, memo = _ref3.memo;

  _ref4 = require("../../samples/kleene"), kleene = _ref4.kleene, leftkleene = _ref4.leftkleene, kleenePredicate = _ref4.kleenePredicate, dightsSpaces = _ref4.dightsSpaces, flatString = _ref4.flatString;

  xexports = {};

  exports.Test = {
    "test kleenePredicate": function(test) {
      var x;

      x = vari('x');
      console.log(solve(begin(settext('123 456'), kleenePredicate(dightsSpaces)(x), flatString(getvalue(x)))));
      return test.done();
    },
    "test kleene": function(test) {
      var x;

      x = vari('x');
      console.log(solve(begin(settext('ab'), kleene(x), flatString(getvalue(x)))));
      test.equal(core.status, core.SUCCESS);
      return test.done();
    }
  };

  xexports.Test = {
    "test leftkleene": function(test) {
      console.log(solve(begin(settext('ab'), leftkleene())));
      test.equal(core.status, core.SUCCESS);
      return test.done();
    }
  };

}).call(this);

/*
//@ sourceMappingURL=test-kleene.map
*/
