// Generated by CoffeeScript 1.6.2
(function() {
  var andp, array, assign, begin, char, compile, core, daoutil, direct, funcall, grammar, identifier, il, jsfun, lamda, nonlocal, number, operator, orp, parsetext, quoteString, repl, solve, string, unaryExpr, util, _, _ref;

  _ = require("underscore");

  solve = (core = require('./core')).solve;

  _ref = util = require('./util'), string = _ref.string, char = _ref.char, number = _ref.number, parsetext = _ref.parsetext, quoteString = _ref.quoteString, identifier = _ref.identifier, begin = _ref.begin, nonlocal = _ref.nonlocal, direct = _ref.direct, jsfun = _ref.jsfun, lamda = _ref.lamda, funcall = _ref.funcall, andp = _ref.andp, orp = _ref.orp, assign = _ref.assign, array = _ref.array;

  operator = (daoutil = require('./daoutil')).operator;

  il = require('./interlang');

  repl = function() {};

  exports.compile = compile = function(code) {
    var path, sexpr;

    sexpr = core.solve(parsetext(grammar, string(exp)));
    path = process.cwd() + '/lib/compiled.js';
    return core.compile(sexpr, path);
  };

  exports.solve = solve = function(exp) {
    var sexpr;

    return sexpr = core.solve(parsetext(grammar, string(exp)));
  };

  unaryExpr = function(exp) {
    return andp(unaryOperator(op), expression(exp));
  };

  grammar = begin(direct(il.begin(il.assign(il.uservar('daoutil'), il.require('./daoutil')), il.assign(il.uservar('operator'), il.attr(il.uservar('daoutil'), il.symbol('operator'))))), assign('atomic', lamda([], orp(identifier(), quoteString(), number()))), assign('binaryExpr', lamda([], andp(assign('x', funcall('atomic')), orp(andp(assign('op', funcall('operator', 'solver')), assign('y', funcall('atomic')), array('op', 'x', 'y')), 'x')))), funcall('binaryExpr'));

}).call(this);

/*
//@ sourceMappingURL=dao.map
*/
